apiVersion: v2
name: beacon
description: Observability stack for Kubernetes - Prometheus, Loki, Tempo, Grafana and Alloy
type: application
annotations:
  licenses: AGPL-3.0-only
version: 3.0.2
appVersion: "3.0"
keywords:
  - observability
  - prometheus
  - loki
  - tempo
  - grafana
  - alloy
maintainers:
  - name: Algonomia
home: https://github.com/Algonomia/beacon
sources:
  - https://github.com/Algonomia/beacon
