{{- if and .Values.prometheus.enabled .Values.discovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ include "beacon.namespace" . }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.componentLabels" "prometheus" | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "beacon.namespace" . }}-prometheus
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.componentLabels" "prometheus" | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "beacon.namespace" . }}-prometheus
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.componentLabels" "prometheus" | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "beacon.namespace" . }}-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: {{ include "beacon.namespace" . }}
{{- end }}
